version: '3.1'

services:
    db:
        image: postgres
        ports:
            - 5432:5432
        environment:
            POSTGRES_PASSWORD: 123qwe
            POSTGRES_USER: moam
            POSTGRES_DB: moam
    adminer:
        image: adminer
        ports:
            - 8080:8080
